language: go

go:
  - 1.10.x

env:
  - GO_ENV=test

services:
  - postgresql

before_script:
  - psql -c 'create database vanpoolmanager;' -U vanpooladmin
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets

go_import_path: github.com/joshgav/vanpool-manager/services/frontend

install:
  - go get github.com/gobuffalo/buffalo/buffalo
  - go get github.com/golang/dep/cmd/dep
  - dep ensure

script: buffalo test
