development:
  dialect:  postgres
  database: {{ envOr "POSTGRES_DB" "vanpoolmanager" }}
  host:     {{ envOr "LOCAL_POSTGRES_HOST" "localhost" }}
  port:     {{ envOr "POSTGRES_PORT" "5432" }}
  user:     {{ envOr "POSTGRES_USER" "vanpooladmin" }}
  password: {{ envOr "POSTGRES_PASSWORD" ""}}
  pool:     5

test:
  dialect:  postgres
  database: {{ envOr "POSTGRES_DB" "vanpoolmanager" }}
  host:     {{ envOr "LOCAL_POSTGRES_HOST" "localhost" }}
  port:     {{ envOr "POSTGRES_PORT" "5432" }}
  user:     {{ envOr "POSTGRES_USER" "vanpooladmin" }}
  password: {{ envOr "POSTGRES_PASSWORD" ""}}
  pool:     5

production:
  dialect:   postgres
  database: {{ envOr "POSTGRES_DB" "vanpoolmanager" }}
  host:     {{ envOr "AZURE_POSTGRES_HOST" "" -}} .postgres.database.azure.com
  user:     {{ envOr "POSTGRES_USER" "vanpooladmin" -}} @ {{- envOr "AZURE_POSTGRES_HOST" "" }}
  password: {{ envOr "POSTGRES_PASSWORD" "" }}
  pool: 5
  options:
    sslmode: require
